let categoryList = [
  "antipasti entradas",
  "para compartir",
  "insalate ensaladas",
  "pizze classiche",
  "pasta tradizionali",
  "paste fresche e ripien",
  "paellas - risottos",
  "paella alicantina",
  "parrilla de bras",
  "salsas caseras",
  "acompañamientos",
  "menu infantil",
  "postre",
]

let list2 = [
"bruschetta prego",
"focaccia con pomodoro, rucola e parmigiano",
"focaccia con formaggio e aglio",
"caprese di mozzarella di bufala con pomodoro raf",
"bruschetta pomodoro, aglio, cipolla, basilico e olio d'oliva",
"antipasti mixto italiano",

"patatas bravas-alioli caseras al estilo prego",
"chopito nacional rebozado",
"gambón al ajillo",
"queso provolone al horno",
"mejillónes al vapor",
"mejillónes estilo prego",
"parrillada de verduras a la brasa",
"calamar nacional rebozado",
"]amón ibérico y queso manchego",
"boquerón nacional rebozado",
"fritura de pescado nacional",
"pata de pulpo a la plancha con pure de patata y albahaca",

"variata",
"cesare originale temperata",
"burrata di bufala",
"salmone affumicato",
"rucola",
"formaggino temperata",

"pizza margherita",
"pizza funghi",
"pizza vegetariana",
"pizza prosciutto",
"pizza salame",
"pizza tonno",
"pizza diavola",
"pizza hawai",
"pizza calabrese",
"pizza carbonara",
"pizza milano",
"quattro stagioni",
"quattro formaggi",
"calzone",
"pizza fantasía (gourmet)",
"pizza parma (gourmet)",
"pizza frutti di mare",
"pizza prego",
"pizz piamontesa(gourmet)",
"pizza fiorentina (gourmet)",
"pizza barbacoa",

"spaghetti bolognese",
"penne arrabbiata",
"spaghetti ai frutti di mare",
"spaghetti carbonara",
"penne con salmon e zucchini",
"penne con pollo",

"tagliatelle al salmone",
"tagliatelle salsicca funghi",
"tagliatelle gamberetti",
"lasagna alla bolognese",
"lasagne vegetali",
"panzerotti di ricotta e spinaci al tartufo",
"gnocchi quattro formaggi con fungi portobello",
"gnocchi alla sorrentina",
"cannellone salmone e spinaci",

"paella de marisco",
"arroz de pollo",
"arroz negro con sepia, coliflor y pimiento",
"fideuà de marisco",
"risotto ai funghi portobello e gorgonzola",
"risotto tartufato con burrata di bufala",

"rollito de solomillo de pollo de corral con bacon y parmesano",
"pechuga de pollo de corral nacional",
"chuletillas de cordero",
"costillar de cerdo",
"entrecóte de ternera",
"extra foie de pato con reducción p.x.",

"salmón",
"dorada",
"calamar de potera plancha",

"crema de pimientas mixtas",
"crema   de champiñiones",
"crema de queso gorgonzola ",
"barbacoa",
"tártara",

"patatas al horno",
"setas portobello con a]o y aove",
"verdura de temporada al vapor con aovey sal",
"mezclum de lechugas",

"plato principal",
"pizza prosciutto cotto",
"spaghetti / penne con tomate",

"panna cotta",
"bola de helado"
]
